server:
  port:
    8090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

spring:
  application:
    name: authentication-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/postgres_database
    username: username
    password: password
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org:
      springframework:
        web=DEBUG:
        validation=DEBUG:
my:
  security:
    jwt-timeout-in-minutes: 60
    refresh-timeout-in-days: 7
    secret-string: "mySecretStringForKeymySecretStringForKeymySecretStringForKey"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ← Без пробелов после запятых!
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true