eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
server:
  port: 8091

spring:
  application:
    name: message-handler-service
  data:
    mongodb:
      uri: mongodb://username:password@mongodb:27017/messages?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: message-handlers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            value:
              default: java.lang.String
            trusted:
              packages: '*' # Разрешить десериализацию всех пакетов

logging:
  level:
    web: debug
    kafka: debug

my:
  messages:
    pagination-quantity: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus  # ← Без пробелов после запятых!
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true